modLoader = "javafml"
loaderVersion = ">=${neoforge_version}"
license = "${mod_license}"
issueTrackerURL = "${git_repository_host}/${git_organization}/${mod_id}/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Steveplays28"
description = '''
${mod_description}
'''
logoFile = "assets/${mod_id}/icon.png"
displayURL = "${git_repository_host}/${git_organization}/${mod_id}"

[[mixins]]
config = "${mod_id}-common.mixins.json"

[mc-publish]
curseforge = "${curseforge_project_id}"
modrinth = "${modrinth_project_id}"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = ">=${neoforge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = ">=${architectury_api_version}"
ordering = "NONE"
side = "BOTH"
